## Importing neccessary modules

In [1]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from nltk.corpus import stopwords
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report

In [2]:
data=fetch_20newsgroups(subset='all',categories=['rec.motorcycles','sci.electronics'])

In [3]:
dir(data)

['DESCR', 'data', 'filenames', 'target', 'target_names']

In [4]:
xtrain,xtest,ytrain,ytest=train_test_split(data.data,data.target,random_state=13)

## Task1

In [5]:
def model_maker(data):
    xtrain,xtest,ytrain,ytest=train_test_split(data.data,data.target,random_state=13)
    TFIDF = TfidfVectorizer(stop_words=stopwords.words('english'))
    xtrain=TFIDF.fit_transform(xtrain)
    xtest=TFIDF.transform(xtest)
    model=MultinomialNB()
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    matrix=confusion_matrix(ypred,ytest)
    report=classification_report(ytest, ypred)
    table=pd.DataFrame({'Ypred':ypred,'Ytest':ytest})
    return report,matrix,table

## Task2

In [6]:
report,matrix,table=model_maker(data)
print('Report')
print(report)

print('Confusion Matrix')

print()
print(matrix)

print()
print('Classification report')

table[:30]

Report
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       228
           1       1.00      0.98      0.99       267

    accuracy                           0.99       495
   macro avg       0.99      0.99      0.99       495
weighted avg       0.99      0.99      0.99       495

Confusion Matrix

[[227   6]
 [  1 261]]

Classification report


Ypred  Ytest
0       1      1
1       0      0
2       0      0
3       0      1
4       1      1
5       1      1
6       1      1
7       0      0
8       1      1
9       1      1
10      1      1
11      0      0
12      1      1
13      0      0
14      0      0
15      0      0
16      0      0
17      0      0
18      0      0
19      1      1
20      0      0
21      0      0
22      0      0
23      0      0
24      1      1
25      0      0
26      0      0
27      1      1
28      1      1
29      0      0

## Task3

In [7]:
data=fetch_20newsgroups(subset='all',categories=['rec.motorcycles','sci.electronics','rec.sport.baseball','comp.graphics'])

In [8]:
def model_maker(data):
    xtrain,xtest,ytrain,ytest=train_test_split(data.data,data.target,random_state=13)
    TFIDF = TfidfVectorizer(stop_words=stopwords.words('english'))
    xtrain=TFIDF.fit_transform(xtrain)
    xtest=TFIDF.transform(xtest)
    model=MultinomialNB()
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    matrix=confusion_matrix(ypred,ytest)
    report=classification_report(ytest, ypred)
    table=pd.DataFrame({'Ypred':ypred,'Ytest':ytest})
    return report,matrix,table,model

report,matrix,table,model=model_maker(data)

print('Report')
print(report)

print('Confusion Matrix')

print()
print(matrix)

print()
print('Classification report')

table[:30]

Report
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       239
           1       0.98      0.96      0.97       246
           2       0.95      0.99      0.97       257
           3       0.98      0.93      0.95       245

    accuracy                           0.96       987
   macro avg       0.97      0.96      0.96       987
weighted avg       0.97      0.96      0.96       987

Confusion Matrix

[[233   0   1  11]
 [  0 237   1   4]
 [  4   6 255   3]
 [  2   3   0 227]]

Classification report


Ypred  Ytest
0       2      2
1       3      3
2       3      3
3       2      1
4       2      2
5       1      1
6       0      0
7       2      2
8       3      3
9       0      0
10      1      3
11      2      2
12      0      0
13      1      1
14      1      1
15      0      0
16      3      3
17      2      3
18      1      1
19      3      3
20      3      3
21      0      0
22      0      0
23      1      1
24      1      1
25      2      2
26      0      0
27      1      1
28      2      2
29      2      2

## Task4

In [9]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data.data)
y = data.target

clf = MultinomialNB()
clf.fit(X, y)

test_data = ["Menu","What are the different parts of a computer?","Playing baseball is good for one's health.","In which games are you interested?",
    "It is the unknown around the corner that turns my wheels.",
    "I am interested in increasing the picture resolution of my computer.",
    "The team might not win if there is rain."]


X_test=vectorizer.transform(test_data)
y_pred=clf.predict(X_test)

for i in range(len(test_data)):
    print(test_data[i], "->", data.target[y_pred[i]])


Menu -> 0
What are the different parts of a computer? -> 1
Playing baseball is good for one's health. -> 3
In which games are you interested? -> 3
It is the unknown around the corner that turns my wheels. -> 0
I am interested in increasing the picture resolution of my computer. -> 0
The team might not win if there is rain. -> 3
